services:
  database:
    image: mysql:8.0
    ports:
      - 8000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=todo-list
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
